/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hb_nativedemo_MyNDk */

#ifndef _Included_hb_nativedemo_MyNDk
#define _Included_hb_nativedemo_MyNDk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hb_nativedemo_MyNDk
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hb_nativedemo_MyNDk_getMyString
  (JNIEnv *, jobject);

/*
 * Class:     hb_nativedemo_MyNDk
 * Method:    fibonacy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hb_nativedemo_MyNDk_fibonacy
  (JNIEnv *, jobject, jint);

/*
 * Class:     hb_nativedemo_MyNDk
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hb_nativedemo_MyNDk_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
