package hb.legsandbuttocksworkout.homeworkout.gym.buttlegs.buttlegspro.buttlegschallenge.utils;

import hb.legsandbuttocksworkout.homeworkout.gym.buttlegs.buttlegspro.buttlegschallenge.BuildConfig;

public class ConsKeys {
    public static String packageName = BuildConfig.APPLICATION_ID;
    public static final String ADMOB_APP_ID = "ca-app-pub-8468661407843417~2062288574";
    public static final String All_EXERCISE_KEY = (packageName + "_All_EXERCISE_KEY");
    public static final int BOTTOM_TAB_1 = 20;
    public static final int BOTTOM_TAB_2 = 22;
    public static final int BOTTOM_TAB_3 = 21;
    public static final String CHALLENGE_TYPE_KEY = (packageName + "_CHALLENGE_TYPE_KEY");
    public static final String EMAIL_FITY_GMAIL = "support@fitfit.am";
    public static final String EXERCISE_CHALLENGE_DAY_TYPE_KEY = (packageName + "_EXERCISE_CHALLENGE_DAY_TYPE_KEY");
    public static final String EXERCISE_DATA_CHALLENGE_DAY_KEY = (packageName + "_EXERCISE_DATA_CHALLENGE_DAY_KEY");
    public static final String EXERCISE_DATA_IS_REST_KEY = (packageName + "_EXERCISE_DATA_IS_REST_KEY");
    public static final String EXERCISE_DATA_KEY = (packageName + "_EXERCISE_DATA_KEY");
    public static final String EXERCISE_DATA_TYPE_KEY = (packageName + "_EXERCISE_DATA_TYPE_KEY");
    public static final String FIRST_METRICS = (packageName + "_FIRSTE_METRICS");
    public static final String INSTA_URL = "https://www.instagram.com/fitfitam/";
    public static final int KEY_GENDER_DEFAULT = 0;
    public static final int KEY_GENDER_FEMALE = 2;
    public static final int KEY_GENDER_MALE = 1;
    public static final String KEY_SETTING_PREFERENCES = (packageName + "_KEY_SETTING_PREFERENCES");
    public static final String LEVEL_DATA_KEY = (packageName + "_LEVEL_DATA_KEY");
    public static final String LEVEL_PREVIEW_HINT = (packageName + "_LEVEL_PREVIEW_HINTt");
    public static final String LEVEL_PREV_DATA = (packageName + "_LEVEL_PREV_DATA");
    public static final String LIST_KEY = "data";
    public static final String NOTIFY_KEY = "notify";
    public static final String PREFS_CHALLENGE_CURRENT_DAY = (packageName + "_CHALLENGE_CURRENT_DAY");
    public static final String PREFS_CUSTOM_WORKOUT = (packageName + "_CUSTOM_WORKOUT_DATA");
    public static final String PREFS_GENDER = (packageName + "_GENDER");
    public static final String PREFS_HAS_ALARM = (packageName + "_PREFS_HAS_ALARM");
    public static final String PREFS_IAP_CUSTOM_WORKOUT = "custom_workout";
    public static final String PREFS_IAP_PRO_PACKAGE = (packageName + "_PRO_PACKAGE");
    public static final String PREFS_IAP_PURCHASE_AVAILABLE = (packageName + "_PURCHASE_AVAILABLE");
    public static final String PREFS_IS_FIRST_TIME = (packageName + "_IS_FIRST_TIME");
    public static final String PREFS_IS_RATED = (packageName + "_RATED");
    public static final String PREFS_IS_RECEMMENDED_CLICKED = (packageName + "__RECEMMENDED_CLICKED");
    public static final String PREFS_LEVEL_LOCK = (packageName + "_LEVEL_LOCK");
    public static final String PREFS_NAME = (packageName + "ABS_DATA");
    public static final String PREFS_READY_TIME = (packageName + "_READY_TIME");
    public static final String PREFS_REMINDER = (packageName + "_REMINDER");
    public static final String PREFS_REMINDER_HINT = (packageName + "_PREFS_RECOMMENDED_HINT");
    public static final String PREFS_REST_TIME = (packageName + "_REST_TIME");
    public static final String PREFS_SETTING_SOUND = (packageName + "_PREFS_SETTING_SOUND");
    public static final String PREFS_WEEK_START = (packageName + "_WEEK_START");
    public static final String REALM_NAME = (packageName + ".db.realm");
    public static String RECOMMENDED_APP_BUTT = "hb.me.homeworkout.gym.buttlegs.buttlegspro";
    public static String RECOMMENDED_APP_PUSH_UPS = "hb.homeworkout.homeworkouts.noequipment.fitnesspro";
    public static final String RECOMMENDED_LOSE_WEIGHT = "hb.me.homeworkout.gym.buttlegs.buttlegspro";
    public static int REQUEST_LEVEL_PREVIEW = 2;
    public static final int VIEW_TYPE_AD = 6;
    public static final int VIEW_TYPE_CHALLENGE = 11;
    public static final int VIEW_TYPE_CHALLENGE_DAY = 9;
    public static final int VIEW_TYPE_CHALLENGE_TITLE = 10;
    public static final int VIEW_TYPE_CUSTOM_WORKOUT = 3;
    public static final int VIEW_TYPE_HEADER = 0;
    public static final int VIEW_TYPE_LABEL = 5;
    public static final int VIEW_TYPE_RATE = 4;
    public static final int VIEW_TYPE_REMINDER = 7;
    public static final int VIEW_TYPE_WEIGHT = 8;
    public static final int VIEW_TYPE_WORKOUT = -1;
    public static final String WEIGHT_COUNT = (packageName + "_WEIGHT_COUNT");
    public static final String WEIGHT_METRICS = (packageName + "_METRICS");
    public static final String WEIGT_LAST_CALENDAR = (packageName + "_WEIGT_LAST_CALENDAR");

}
